### ISSUE TITLE
alternate notifications methods

### ISSUE THREAD

**Issue by dkebler** [docwhat/chronic#3]
Been using chucks script for some time.  Works great.  
Came across your repo.

The only notification option is email via that line in crontab but now that a go binary is at hand it would be cool to hook this not just to an email in crontab but allow notifications to other services like push safer, etc.

I'm not a go programmer (mostly node).   If I had written this in node I would set up to tee to plugins like this https://www.npmjs.com/package/pushsafer-notifications.  Most notification services have written their own package for node.  Maybe for go as well?

**Comment by docwhat** [comment]
I think chronic should remain as minimal as possible to prevent confusion and bugs. 

I think it would be a cool standalone binary though.  You could pipe the output to it and it would send the output a service. 

Or you could hook it up to a mail filter. 

I think IFTTT has a way to hook incoming email into their workflows. 

I like your idea and hope you take a try at it. 😃

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
